import { Scenerio } from './scenerio.model';

export const SCENERIO: Scenerio[] = [
 new Scenerio(
   1,
   "Explore the Foothills",
   "While wandering through the trees, you see a creature, about the size of a dog.  What do you do?",
   "Try and communicate to it, hoping it could lead you to a food source.",
   "Try to kill and eat it.",
    2,
    3,
    ),
  new Scenerio(
    2,
    "Communicate with the Creature",
    "The creature turns out to be one of the wisest in the galaxy.  He wants to teach you.  What do you do?",
    "Say yes, and embark on this new journey of knowledge.  He IS a little hazey on what he says he knows.",
    "Say no, and ask again on where to find food.",
     4,
     5,
     ),
   new Scenerio(
     3,
     "Fight with the Creature",
     "The creature turns out to be a feirce fighter and captures you.  He takes you to his dark, damp cave.  What do you do?",
     "You search for something sharp to cut the rope binding your hands.",
     "You try pleading with it, saying you are the heir to a fortune and will give it money if he releases you.",
      6,
      7,
      ),
    new Scenerio(
      4,
      "Listen to Creature",
      "You end up learning the answer to infinite bliss.  What do you do with it?",
      "You enter into a world of bliss, happily ever after.",
      "You go back home and prostlatize the creature\'s teachings and live a happy life.",
       1,
       1,
       ),
     new Scenerio(
       5,
       "The search for food.",
       "You end up finding a Popeyes Chicken!  What do you do with it?",
       "You eat so much fried chicken you enter into an infinite coma.",
       "You buy all the chicken and bring it back home and watch the latest sporting match with the greasiest fingers.  Long live fried chicken.",
        1,
        1,
        ),
    new Scenerio(
        6,
        "The search for freedom.",
        "You end up freeing yourself and wait for just the right moment to make your escape.  What do you do?",
        "You wait till the creature falls asleep and smash it with a big rock.  You flee the planet and return home, super HUNGRY!",
        "You can't escape and wither away into nothing.",
         1,
         1,
         ),
     new Scenerio(
         7,
         "The great bribe",
         "He listens to you and become great friends out of financial gain.  What do you do?",
         "End of story",
         "End of story",
          1,
          1,
          ),
];
